debug docs
Signed-off-by: tao.yang <tao.yang@daocloud.io>

diff --git a/.github/workflows/call-release-doc.yaml b/.github/workflows/call-release-doc.yaml
--- a/.github/workflows/call-release-doc.yaml
+++ b/.github/workflows/call-release-doc.yaml
@@ -20,6 +20,18 @@ on:
         description: 'branch, tag, sha'
         required: true
         default: main
+      docs_tag:
+        description: "defines the generated documentation version"
+        required: false
+        type: string
+      set_latest:
+        description: "set the version of the document to the latest."
+        type: choice
+        required: false
+        default: true
+        options:
+          - "true"
+          - "false"
 
 permissions: write-all
 
@@ -31,85 +43,88 @@ env:
   PR_REVIWER: weizhoublue
 
 jobs:
-  prepare_doc:
-    name: prepare doc
+  get_ref:
     runs-on: ubuntu-latest
     outputs:
-      ref: ${{ steps.get_ref.outputs.ref }}
-      submit: ${{ steps.get_ref.outputs.submit }}
+      ref: ${{ env.REF }}
+      submit: ${{ env.SUBMIT }}
+      docs_tag: ${{ env.DOCS_TAG }}
+      set_latest: ${{ env.SET_LATEST }}
     steps:
       - name: Get Ref
         id: get_ref
         run: |
           pwd
           ls
-          if ${{ inputs.ref != '' }}; then
-              echo "call by workflow_call"
-              echo ::set-output name=ref::${{ inputs.ref }}
-              echo ::set-output name=submit::${{ inputs.submit }}
-          elif ${{ github.event_name == 'workflow_dispatch' }} ; then
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
               echo "call by workflow_dispatch"
-              echo ::set-output name=ref::${{ github.event.inputs.ref }}
-              echo ::set-output name=submit::true
+              echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+              echo "SUBMIT=true" >> $GITHUB_ENV
+              if ${{ github.event.inputs.docs_tag != '' }} ; then
+                  echo "DOCS_TAG=${{ github.event.inputs.docs_tag }}" >> $GITHUB_ENV
+              else
+                  echo "DOCS_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+              fi
+              echo "SET_LATEST=${{ github.event.inputs.set_latest }}" >> $GITHUB_ENV
+          elif ${{ inputs.ref != '' }}; then 
+              echo "call by workflow_call"
+              echo "REF=${{ inputs.ref }}" >> $GITHUB_ENV
+              echo "SUBMIT=${{ inputs.submit }}" >> $GITHUB_ENV
+              echo "DOCS_TAG=${{ inputs.ref }}" >> $GITHUB_ENV
           else
               echo "unexpected event: ${{ github.event_name }}"
               exit 1
           fi
 
-      - name: Checkout Code
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ steps.get_ref.outputs.ref }}
-
-      - name: Build Site
-        run: |
-          make build_doc
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: website_package_artifact
-          path: docs/site.tar.gz
-          retention-days: 0
-          if-no-files-found: error
-
-  create_pr:
-    name: Create PR
-    needs: prepare_doc
-    if: ${{ needs.prepare_doc.outputs.submit == 'true' }}
+  build_doc:
     runs-on: ubuntu-latest
+    needs: get_ref
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
+          fetch-depth: 0
           ref: ${{ env.MERGE_BRANCH }}
-
-      - name: backup charts
+    
+      - name: Extract Version
+        id: extract
         run: |
-          rm -rf ./_backupCharts
-          mkdir ./_backupCharts
-          cp -f ${{ env.DEST_DIRECTORY }}/index.yaml ./_backupCharts
-          cp -rf ${{ env.DEST_DIRECTORY }}/charts ./_backupCharts/charts
-          rm -rf ${{ env.DEST_DIRECTORY }}
-          mkdir ${{ env.DEST_DIRECTORY }}
+          pattern="([0-9]+\.[0-9]+)\.[0-9]+"
+          VERSION=""
+          if [[ ${{ inputs.ref }} =~ $pattern ]]; then
+            VERSION="${BASH_REMATCH[1]}.0"
+          else
+            echo "error, invalid version " && exit 1
+          fi
+          if [ -e "docs/$VERSION" ]; then
+              echo "SET_LATEST=false" >> $GITHUB_ENV
+          else
+              echo "SET_LATEST=true" >> $GITHUB_ENV
+          fi
+          echo "DOCS_TAG=$VERSION" >> $GITHUB_ENV
+            
 
-      - name: Download Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: site_artifact
-          path: ${{ env.DEST_DIRECTORY }}
-
-      - name: Untar Artifact And Restore Charts
+      - name: build doc
         run: |
-          cd ${{ env.DEST_DIRECTORY }}
-          tar -xzvf site.tar.gz
-          rm -f site.tar.gz
-          cp -rf ../_backupCharts/* ./
-          rm -rf ../_backupCharts
+          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material==8.5.11
+          git config user.email "robot@example.com"
+          git config user.name "robot"
+          cp ./docs/mkdocs.yml ./
+          if ${{ needs.get_ref.outputs.set_latest == 'true' }} ;then
+              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} --update-aliases ${{ needs.get_ref.outputs.docs_tag }} latest
+              mike set-default --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} latest
+          else
+              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} ${{ needs.get_ref.outputs.docs_tag }}
+              echo "the version of the document does not need to be set to the latest."
+          fi
+          rm -rf ./site
+          rm -rf ./mkdocs.yml
+          git checkout -f  ${{ env.MERGE_BRANCH }}
 
       # Allow auto-merge on general
       - name: Create Pull Request
         id: create_pr
+        if: ${{ needs.get_ref.outputs.submit == 'true' }}
         uses: peter-evans/create-pull-request@v5.0.2
         with:
           title: "robot update website from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
